spring.application.name=authservice
authServiceType=localAuthService
passedEncodedKey=h1w8ZbXrj6JFcmnPuNjaouOSVZz5wIsmj8OMa/WpO6c=

server.port=8090

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/authservice
spring.datasource.username=authserviceuser
#spring.datasource.password=secret
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true